---

# Requirements
- import_tasks: requirements.yml
  tags:
    - manala_npm

# Update
- import_tasks: update.yml
  when: manala_npm['update']|default(false)
  tags:
    - manala_npm
    - manala_npm.update
    - manala.update

# Packages
- import_tasks: packages.yml
  tags:
    - manala_npm
